version: '3.1'
<<<<<<< HEAD
=======

>>>>>>> 28aeb99dd34aca0e9c818397809b534164d566d6
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
<<<<<<< HEAD
      - 27017:27017
=======
    - 27017:27017

>>>>>>> 28aeb99dd34aca0e9c818397809b534164d566d6
  mongo-express:
    image: mongo-express
    restart: always
    ports:
<<<<<<< HEAD
      - 8081:8081
=======
    - 8081:8081
>>>>>>> 28aeb99dd34aca0e9c818397809b534164d566d6
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
<<<<<<< HEAD
      - mongo
=======
    - mongo
>>>>>>> 28aeb99dd34aca0e9c818397809b534164d566d6
