FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app
 
# Copy everything and build
COPY . ./
 
RUN dotnet restore TodoApp/TodoApp.csproj
RUN dotnet publish TodoApp/TodoApp.csproj -c Release -o out
 

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "TodoApp.dll"]